allow custom request headers
adobe/aem-headless-client-js pull request #38
Opened 2022-11-04 22:09 UTC by jihuang-adobe

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-11-30 11:14 UTC, ghenzler commented
@jihuang-adobe What is your use case that requires to set an additional header? Do you have some intermediate infrastructure that requires that header? 

(I'm asking because potentially it could be better to explicitly provide the functionality over this generic approach, but it depends on if it is very specific to your setup or not)

2022-11-30 14:33 UTC, jihuang-adobe commented
Hi @ghenzler.  I am currently have AEM graphql endpoint behind a proxy.  The proxy can potentially take a list of custom headers, so I thought it would be convenient if the AEM Headless Client would accept custom headers as an option.

2022-12-08 15:06 UTC, easingthemes requested changes

2022-12-08 15:28 UTC, easingthemes commented on src/index.js
> +        ...this.headers
Better to reverse order, to allow single request to override global headers

2022-12-09 01:12 UTC, jihuang-adobe reviewed
updated according to feedback

2022-12-11 16:42 UTC, merged